### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by RafalBuchner** [RafalBuchner/StemPlow#2]
some problems: will add more if I find any
- [x] fix it: it doesn't work on line segments
- [x] fix it: it weirdly updates anchor data on click

**Comment by RafalBuchner** [comment]
Getting:
```
Traceback (most recent call last):
  File "lib/eventTools/eventManager.pyc", line 165, in callObserver_withMethod_forEvent_withInfo_
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.9/mojo/subscriber.py", line 1659, in _roboFontCallback
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.9/mojo/subscriber.py", line 3320, in start
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.9/mojo/subscriber.py", line 3337, in fire
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.9/mojo/subscriber.py", line 1677, in _roboFontCoalescerCallback
  File "/Users/rafalbuchner/Library/Application Support/RoboFont/plugins/StemPlow.roboFontExt/lib/StemPlowSubscriber.py", line 285, in glyphEditorDidUndo
  File "/Users/rafalbuchner/Library/Application Support/RoboFont/plugins/StemPlow.roboFontExt/lib/StemPlowSubscriber.py", line 279, in glyphEditorDidMouseDrag
  File "/Users/rafalbuchner/Library/Application Support/RoboFont/plugins/StemPlow.roboFontExt/lib/StemPlowSubscriber.py", line 587, in getThicknessData
  File "/Users/rafalbuchner/Library/Application Support/RoboFont/plugins/StemPlow.roboFontExt/lib/StemPlowSubscriber.py", line 437, in getGuidesAndAnchoredPoint
  File "/Users/rafalbuchner/Library/Application Support/RoboFont/plugins/StemPlow.roboFontExt/lib/StemMath.py", line 125, in calculateGuidesBasedOnT
  File "/Users/rafalbuchner/Library/Application Support/RoboFont/plugins/StemPlow.roboFontExt/lib/StemMath.py", line 279, in calcSeg
AssertionError: calcSeg ERROR: t is not a float
```
when changing glyph in GlyphEditor from one, with anchored ruler

- [x] FIX IT!!!!

**Comment by RafalBuchner** [comment]
- [x] "trigger hotkey" toggles visibility of the StemPlow when "always" setting is on
